#pragma once
#include <array>
#include "game.hpp"

// Canonical spreadsheet order; gameplay has twice the weight in the browser.
inline constexpr std::array<std::string_view, 5> REVIEW_KEYS{
    "story", "gameplay", "graphics", "audio", "special"};
// Human-readable dimension headings used in tables and forms.
inline constexpr std::array<std::string_view, 5> REVIEW_LABELS{
    "Story/Lore", "Gameplay", "Graphics", "Audio", "Special"};

// Persisted inputs only; the overall score is never stored or server-computed.
struct GameReviewInput
{
    // Missing dimensions keep a draft incomplete; fractional scores are valid.
    std::array<std::optional<double>, 5> scores;
    // Optional overall MacroDown review text; empty means absent.
    std::string text;
};

// A review inherits its identity and owner from its tracked game.
struct GameReviewRecord
{
    // Foreign key to GameTracking, also the unique review identity.
    int64_t game_id;
    // Validated source fields.
    GameReviewInput input;
    // UTC timestamps generated by storage, preserved across game renames.
    int64_t added;
    int64_t updated;
};

// Validates all submitted score and text fields together for form redisplay.
E<GameReviewInput> validateReview(const GameFields &fields);
// Converts stored review inputs to editable source fields.
GameFields reviewFields(const GameReviewInput &input);
